---

## # 카테고리 매핑 결과 분석

: 2018.12.26일 기준, 라이브딜("표준 카테고리")과 배송2.0("물리 카테고리")의 카테고리 매핑 작업이 이루어졌다.
<br/> 따라서, 카테고리 매핑 작업 이후의 카테고리 대표값들의 변화를 살펴 볼 필요가 있다.

## # cur 데이터 - TOBE기준

In [6]:
import pandas as pd
from glob import glob

glob("*")

cur = pd.read_json('part-00000-ee5d3a14-1224-4fd6-9d5b-f91e64c39603-c000.json', lines=True)

cur.head(5)

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt,rcp,scateCd,totalOrderUserCnt
0,231010101,231000000,231010000,3302,0.120908,231010100,27310
1,231010201,231000000,231010000,2211,0.099846,231010200,22144
2,231010202,231000000,231010000,2962,0.080002,231010200,37024
3,231010203,231000000,231010000,4475,0.128378,231010200,34858
4,231010204,231000000,231010000,6115,0.111494,231010200,54846

In [5]:
cur.shape

(1575, 7)

In [21]:
cur.head(5)

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt,rcp,scateCd,totalOrderUserCnt
0,231010101,231000000,231010000,3302,0.120908,231010100,27310
1,231010201,231000000,231010000,2211,0.099846,231010200,22144
2,231010202,231000000,231010000,2962,0.080002,231010200,37024
3,231010203,231000000,231010000,4475,0.128378,231010200,34858
4,231010204,231000000,231010000,6115,0.111494,231010200,54846

In [7]:
cur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1575 entries, 0 to 1574
Data columns (total 7 columns):
dcateCd                    1575 non-null int64
lcateCd                    1575 non-null int64
mcateCd                    1575 non-null int64
moreT2TimesOrderUserCnt    1575 non-null int64
rcp                        1575 non-null float64
scateCd                    1575 non-null int64
totalOrderUserCnt          1575 non-null int64
dtypes: float64(1), int64(6)
memory usage: 86.2 KB

In [15]:
cur.dcateCd.nunique()

1575

---

## # prev 데이터

In [7]:
prev = pd.read_json('./prev/part-00000-d2a192e1-c5e6-452b-b1a0-51fb576e738c-c000.json', lines=True)

In [8]:
prev.head()

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt,rcp,scateCd,totalOrderUserCnt
0,4100000,1100000,2100000,4021,0.226280,3100000,17770
1,4100001,1100000,2100000,117,0.131609,3100000,889
2,4100002,1100014,2100084,82,0.098321,3100488,834
3,4100003,1100000,2100000,840,0.113116,3100000,7426
4,4100004,1100000,2100000,50,0.142450,3100000,351

In [11]:
prev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7007 entries, 0 to 7006
Data columns (total 7 columns):
dcateCd                    7007 non-null int64
lcateCd                    7007 non-null int64
mcateCd                    7007 non-null int64
moreT2TimesOrderUserCnt    7007 non-null int64
rcp                        7007 non-null float64
scateCd                    7007 non-null int64
totalOrderUserCnt          7007 non-null int64
dtypes: float64(1), int64(6)
memory usage: 383.3 KB

---

## # cur / prev 카테고리 살펴보자

In [11]:
# prev에서 표준카테고리(라이브딜) 배송상품군 카테고리 수

prev[~(prev.dcateCd < 200000000)].shape[0]

1542

In [12]:
# 표준 카테고리 이외의 배송상품군 카테고리 수(or 표준 카테고리 이외의 카테고리 수)

prev[(prev.dcateCd < 200000000)].shape[0]

5465

In [13]:
# prev에는, 배송상품군 이외에는 들어있지 않다.
prev[(prev.dcateCd >= 300000000)].shape[0]

0

---

## # prev_live : 표준 카테고리 & 배송상품군

In [14]:
prev_live = prev[~(prev.dcateCd < 200000000)]

In [22]:
prev.columns

Index(['dcateCd', 'lcateCd', 'mcateCd', 'moreT2TimesOrderUserCnt', 'rcp',
       'scateCd', 'totalOrderUserCnt'],
      dtype='object')

## # prev - cur 데이터 merge한다 : 매핑함으로, 통계량이 어느정도 변하는지 살펴볼거야

In [22]:
# merge의 key값 정의

key = ['dcateCd', 'lcateCd', 'mcateCd', 'scateCd']

In [23]:
prev_cur = pd.merge(prev_live, cur , how='right', on= key)

In [24]:
prev_cur.columns

Index(['dcateCd', 'lcateCd', 'mcateCd', 'moreT2TimesOrderUserCnt_x', 'rcp_x',
       'scateCd', 'totalOrderUserCnt_x', 'moreT2TimesOrderUserCnt_y', 'rcp_y',
       'totalOrderUserCnt_y'],
      dtype='object')

In [25]:
prev_cur.tail()

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y
1570,238060201,238000000,238060000,NaN,NaN,238060200,NaN,0,0.000000,3
1571,238060301,238000000,238060000,NaN,NaN,238060300,NaN,26,0.037627,691
1572,238060302,238000000,238060000,NaN,NaN,238060300,NaN,259,0.119190,2173
1573,239010203,239000000,239010000,NaN,NaN,239010200,NaN,1,0.111111,9
1574,239010603,239000000,239010000,NaN,NaN,239010600,NaN,1,0.125000,8

In [26]:
prev_cur.isnull()

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1545,False,False,False,True,True,False,True,False,False,False
1546,False,False,False,True,True,False,True,False,False,False
1547,False,False,False,True,True,False,True,False,False,False
1548,False,False,False,True,True,False,True,False,False,False
1549,False,False,False,True,True,False,True,False,False,False
1550,False,False,False,True,True,False,True,False,False,False
1551,False,False,False,True,True,False,True,False,False,False
1552,False,False,False,True,True,False,True,False,False,False
1553,False,False,False,True,True,False,True,False,False,False
1554,False,False,False,True,True,False,True,False,False,False
1555,False,False,False,True,True,False,True,False,False,False
1556,False,False,False,True,True,False,True,False,False,False
1557,False,False,False,True,True,False,True,False,False,False
1558,False,False,False,True,True,False,True,False,False,False
1559,False,False,False,True,True,False,True,False,False,False
1560,False,False,False,True,True,False,True,False,False,False
1561,False,False,False,True,True,False,True,False,False,False
1562,False,False,False,True,True,False,True,False,False,False
1563,False,False,False,True,True,False,True,False,False,False
1564,False,False,False,True,True,False,True,False,False,False
1565,False,False,False,True,True,False,True,False,False,False
1566,False,False,False,True,True,False,True,False,False,False
1567,False,False,False,True,True,False,True,False,False,False
1568,False,False,False,True,True,False,True,False,False,False
1569,False,False,False,True,True,False,True,False,False,False
1570,False,False,False,True,True,False,True,False,False,False
1571,False,False,False,True,True,False,True,False,False,False
1572,False,False,False,True,True,False,True,False,False,False
1573,False,False,False,True,True,False,True,False,False,False
1574,False,False,False,True,True,False,True,False,False,False

In [27]:
prev_cur.isnull().any() # NaN 값을 가진 columns만 확인

dcateCd                      False
lcateCd                      False
mcateCd                      False
moreT2TimesOrderUserCnt_x     True
rcp_x                         True
scateCd                      False
totalOrderUserCnt_x           True
moreT2TimesOrderUserCnt_y    False
rcp_y                        False
totalOrderUserCnt_y          False
dtype: bool

In [28]:
prev_cur.isnull().any().any()  # 어딘가에는 NaN값이 있는 데이터인가? 를 확인 할 수 있다.

True

In [29]:
prev_cur.isnull().sum()  # 이정도의 null값 존재한다 -> cur데이터에는 category 33개 새로 생겼기 때문에!

dcateCd                       0
lcateCd                       0
mcateCd                       0
moreT2TimesOrderUserCnt_x    33
rcp_x                        33
scateCd                       0
totalOrderUserCnt_x          33
moreT2TimesOrderUserCnt_y     0
rcp_y                         0
totalOrderUserCnt_y           0
dtype: int64

In [30]:
prev_cur_new =prev_cur[prev_cur.rcp_x.isnull()]  # 33개의 카테고리 확인 할 수 있다.

In [31]:
prev_cur_new.columns

Index(['dcateCd', 'lcateCd', 'mcateCd', 'moreT2TimesOrderUserCnt_x', 'rcp_x',
       'scateCd', 'totalOrderUserCnt_x', 'moreT2TimesOrderUserCnt_y', 'rcp_y',
       'totalOrderUserCnt_y'],
      dtype='object')

## # prev_cur 데이터를 이용해,  cur에서 새로 생긴 카테고리 정보 확인

In [35]:
# cur에서 새로 생긴 33개의 카테고리 확인!   - 새로 생겼다는 의미은 무엇인가?

prev_cur_new[['dcateCd', 'lcateCd', 'mcateCd', 'moreT2TimesOrderUserCnt_y', 'rcp_y',
       'totalOrderUserCnt_y']]

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y
1542,232010105,232000000,232010000,2,0.500000,4
1543,232010201,232000000,232010000,8,0.063492,126
1544,232010203,232000000,232010000,4,0.137931,29
1545,232020101,232000000,232020000,5,0.384615,13
1546,232030504,232000000,232030000,553,0.172921,3198
1547,232060504,232000000,232060000,1,0.013699,73
1548,232061201,232000000,232060000,21,0.192661,109
1549,232062004,232000000,232060000,1,0.083333,12
1550,232063106,232000000,232060000,22,0.372881,59
1551,232063109,232000000,232060000,5,0.333333,15
1552,232064001,232000000,232060000,65,0.224138,290
1553,232064003,232000000,232060000,4,0.102564,39
1554,232064004,232000000,232060000,9,0.195652,46
1555,232064005,232000000,232060000,13,0.109244,119
1556,232070409,232000000,232070000,2,0.071429,28
1557,232070410,232000000,232070000,7,0.125000,56
1558,232070412,232000000,232070000,30,0.125523,239
1559,233040112,233000000,233040000,317,0.072490,4373
1560,233040116,233000000,233040000,14,0.041420,338
1561,235010103,235000000,235010000,263,0.134184,1960
1562,235010105,235000000,235010000,896,0.119007,7529
1563,235010111,235000000,235010000,956,0.153550,6226
1564,235010401,235000000,235010000,794,0.105923,7496
1565,235010402,235000000,235010000,240,0.130364,1841
1566,235010403,235000000,235010000,345,0.116593,2959
1567,235010504,235000000,235010000,431,0.110089,3915
1568,235010505,235000000,235010000,742,0.171521,4326
1569,238010206,238000000,238010000,0,0.000000,5
1570,238060201,238000000,238060000,0,0.000000,3
1571,238060301,238000000,238060000,26,0.037627,691
1572,238060302,238000000,238060000,259,0.119190,2173
1573,239010203,239000000,239010000,1,0.111111,9
1574,239010603,239000000,239010000,1,0.125000,8

## # prev_cur 데이터를 이용해,  공통 1542개 카테고리 정보 확인

In [38]:
prev_cur_common = prev_cur[~prev_cur.rcp_x.isnull()]

In [39]:
prev_cur_common.head()

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y
0,231010101,231000000,231010000,2598.0,0.111512,231010100,23298.0,3302,0.120908,27310
1,231010201,231000000,231010000,1228.0,0.105471,231010200,11643.0,2211,0.099846,22144
2,231010202,231000000,231010000,2962.0,0.080002,231010200,37024.0,2962,0.080002,37024
3,231010203,231000000,231010000,3533.0,0.126368,231010200,27958.0,4475,0.128378,34858
4,231010204,231000000,231010000,5386.0,0.107541,231010200,50083.0,6115,0.111494,54846

## # 카테고리 매핑으로 인해 통계량들의 업데이트 된 정보를 보고싶다(rcp의 차이라던지, 고객수의 차이 등)

In [66]:
# 이렇게 하면 되긴 하지만.. 경고 밣생

prev_cur_common['e'] = pd.Series(prev_cur_common.rcp_y - prev_cur_common.rcp_x, index=prev_cur_common.index)

/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [62]:
# 이렇게 해도.. 되긴 하지만.. 경고 밣생

prev_cur_common["rcp_diff"] = prev_cur_common.rcp_y - prev_cur_common.rcp_x

/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [ ]:
# 이런식으로 하는게 적당하다네!

df1 = prev_cur_common.assign(rcp_diff=pd.Series(prev_cur_common.rcp_y - prev_cur_common.rcp_x).valeus )

### # rcp_diff 생성

In [40]:
# values 따로 안해도 되겠다.

df2 = prev_cur_common.assign(rcp_diff=prev_cur_common.rcp_y - prev_cur_common.rcp_x)

---

In [41]:
df2

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y,rcp_diff
0,231010101,231000000,231010000,2598.0,0.111512,231010100,23298.0,3302,0.120908,27310,0.009396
1,231010201,231000000,231010000,1228.0,0.105471,231010200,11643.0,2211,0.099846,22144,-0.005625
2,231010202,231000000,231010000,2962.0,0.080002,231010200,37024.0,2962,0.080002,37024,0.000000
3,231010203,231000000,231010000,3533.0,0.126368,231010200,27958.0,4475,0.128378,34858,0.002010
4,231010204,231000000,231010000,5386.0,0.107541,231010200,50083.0,6115,0.111494,54846,0.003953
5,231010301,231000000,231010000,189.0,0.082210,231010300,2299.0,298,0.099333,3000,0.017124
6,231010401,231000000,231010000,3412.0,0.214093,231010400,15937.0,4217,0.194457,21686,-0.019636
7,231010402,231000000,231010000,9982.0,0.129440,231010400,77117.0,13551,0.134183,100989,0.004743
8,231010403,231000000,231010000,4977.0,0.109166,231010400,45591.0,6260,0.114254,54790,0.005088
9,231010404,231000000,231010000,863.0,0.082909,231010400,10409.0,932,0.083775,11125,0.000866
10,231010405,231000000,231010000,3185.0,0.132449,231010400,24047.0,3976,0.133908,29692,0.001459
11,231010501,231000000,231010000,1257.0,0.092631,231010500,13570.0,1754,0.100724,17414,0.008093
12,231010502,231000000,231010000,4382.0,0.086575,231010500,50615.0,5515,0.092659,59519,0.006084
13,231010503,231000000,231010000,475.0,0.105392,231010500,4507.0,475,0.105392,4507,0.000000
14,231010601,231000000,231010000,1059.0,0.060660,231010600,17458.0,1433,0.062799,22819,0.002139
15,231010602,231000000,231010000,3953.0,0.109690,231010600,36038.0,4799,0.114050,42078,0.004360
16,231010603,231000000,231010000,22.0,0.145695,231010600,151.0,22,0.145695,151,0.000000
17,231010604,231000000,231010000,7782.0,0.139345,231010600,55847.0,9459,0.144157,65616,0.004812
18,231010605,231000000,231010000,2101.0,0.139185,231010600,15095.0,2863,0.151321,18920,0.012136
19,231010606,231000000,231010000,5444.0,0.154584,231010600,35217.0,6520,0.155305,41982,0.000720
20,231010607,231000000,231010000,1346.0,0.089175,231010600,15094.0,1651,0.088412,18674,-0.000763
21,231020101,231000000,231020000,1003.0,0.216959,231020100,4623.0,1157,0.181462,6376,-0.035497
22,231020102,231000000,231020000,3708.0,0.108256,231020100,34252.0,3995,0.109617,36445,0.001361
23,231020201,231000000,231020000,158.0,0.092075,231020200,1716.0,158,0.092075,1716,0.000000
24,231020202,231000000,231020000,9182.0,0.205953,231020200,44583.0,9587,0.209383,45787,0.003430
25,231020203,231000000,231020000,238.0,0.113712,231020200,2093.0,276,0.121212,2277,0.007500
26,231020301,231000000,231020000,325.0,0.096496,231020300,3368.0,587,0.127609,4600,0.031112
27,231020302,231000000,231020000,1308.0,0.136620,231020300,9574.0,1546,0.142056,10883,0.005436
28,231020303,231000000,231020000,45.0,0.115385,231020300,390.0,45,0.115385,390,0.000000
29,231020304,231000000,231020000,707.0,0.151392,231020300,4670.0,805,0.152030,5295,0.000638
...,...,...,...,...,...,...,...,...,...,...,...
1512,244030206,244000000,244030000,4200.0,0.111149,244030200,37787.0,4200,0.111149,37787,0.000000
1513,244030301,244000000,244030000,2291.0,0.105659,244030300,21683.0,2291,0.105659,21683,0.000000
1514,244030401,244000000,244030000,8083.0,0.143578,244030400,56297.0,8083,0.143578,56297,0.000000
1515,244030402,244000000,244030000,2424.0,0.124563,244030400,19460.0,2424,0.124563,19460,0.000000
1516,244030501,244000000,244030000,665.0,0.082261,244030500,8084.0,665,0.082261,8084,0.000000
1517,244030502,244000000,244030000,22404.0,0.182691,244030500,122633.0,22404,0.182688,122635,-0.000003
1518,244030503,244000000,244030000,12020.0,0.138498,244030500,86788.0,12020,0.138498,86788,0.000000
1519,244030504,244000000,244030000,69635.0,0.257575,244030500,270348.0,69635,0.257575,270348,0.000000
1520,244030505,244000000,244030000,20494.0,0.164079,244030500,124903.0,20498,0.164086,124922,0.000007
1521,244030506,244000000,244030000,19725.0,0.175940,244030500,112112.0,19725,0.175940,112112,0.000000
1522,244030507,244000000,244030000,41704.0,0.236409,244030500,176406.0,41711,0.236418,176429,0.000009
1523,244030508,244000000,244030000,1104.0,0.074253,244030500,14868.0,1104,0.074253,14868,0.000000
1524,244030601,244000000,244030000,111524.0,0.360022,244030600,309770.0,111524,0.360022,309770,0.000000
1525,244030602,244000000,244030000,4916.0,0.152567,244030600,32222.0,4916,0.152562,32223,-0.000005
1526,244030603,244000000,244030000,5395.0,0.188947,244030600,28553.0,5395,0.188947,28553,0.000000
1527,244030604,244000000,244030000,1415.0,0.245660,244030600,5760.0,1415,0.245660,5760,0.000000
1528,244030605,244000000,244030000,369.0,0.094907,244030600,3888.0,369,0.094907,3888,0.000000
1529,244030606,244000000,244030000,1275.0,0.063807,244030600,19982.0,1275,0.063807,19982,0.000000
1530,244030607,244000000,244030000,11302.0,0.195428,244030600,57832.0,11303,0.195439,57834,0.000011
1531,244030701,244000000,244030000,6352.0,0.099503,244030700,63837.0,6352,0.099503,63837,0.000000
1532,244030702,244000000,244030000,9012.0,0.121843,244030700,73964.0,9012,0.121843,73964,0.000000
1533,244030801,244000000,244030000,779.0,0.097485,244030800,7991.0,779,0.097485,7991,0.000000
1534,244030802,244000000,244030000,20564.0,0.158938,244030800,129384.0,20564,0.158938,129384,0.000000
1535,244030803,244000000,244030000,51327.0,0.197901,244030800,259357.0,51327,0.197901,259357,0.000000
1536,244030804,244000000,244030000,265692.0,0.316937,244030800,838313.0,265692,0.316937,838313,0.000000
1537,244030805,244000000,244030000,2330.0,0.072380,244030800,32191.0,2330,0.072380,32191,0.000000
1538,244030806,244000000,244030000,577.0,0.068544,244030800,8418.0,577,0.068544,8418,0.000000
1539,244030901,244000000,244030000,2245.0,0.180104,244030900,12465.0,2245,0.180104,12465,0.000000
1540,244030902,244000000,244030000,52074.0,0.204868,244030900,254183.0,52077,0.204849,254222,-0.000020
1541,245010101,245000000,245010000,91.0,0.085768,245010100,1061.0,91,0.085768,1061,0.000000

In [76]:
# 232010112 데이터 확인

df2[df2.dcateCd == 232010112]

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y,rcp_diff
98,232010112,232000000,232010000,86.0,0.118132,232010100,728.0,1658,0.666935,2486,0.548803

In [44]:
df2.sort_values(by="rcp_diff", ascending=False, inplace=True) # rcp_diff로 단순하게 정렬! -또한,  여러개의 columns으로 sorting 할 수 있다!

In [45]:
df2

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y,rcp_diff
98,232010112,232000000,232010000,86.0,0.118132,232010100,728.0,1658,0.666935,2486,0.548803
568,233090606,233000000,233090000,2.0,0.040000,233090600,50.0,279,0.472881,590,0.432881
124,232040102,232000000,232040000,0.0,0.000000,232040100,24.0,61,0.371951,164,0.371951
146,232050207,232000000,232050000,1.0,0.014085,232050200,71.0,120,0.363636,330,0.349552
564,233090602,233000000,233090000,42.0,0.253012,233090600,166.0,584,0.593496,984,0.340484
97,232010111,232000000,232010000,0.0,0.000000,232010100,3.0,41,0.308271,133,0.308271
765,236010101,236000000,236010000,6904.0,0.157460,236010100,43846.0,256310,0.463363,553152,0.305902
158,232050701,232000000,232050000,1.0,0.013889,232050700,72.0,307,0.311044,987,0.297155
196,232060501,232000000,232060000,0.0,0.000000,232060500,2.0,11,0.255814,43,0.255814
104,232010208,232000000,232010000,0.0,0.000000,232010200,25.0,36,0.240000,150,0.240000
135,232040201,232000000,232040000,0.0,0.000000,232040200,17.0,244,0.237585,1027,0.237585
94,232010108,232000000,232010000,4.0,0.047619,232010100,84.0,874,0.272869,3203,0.225250
323,232070503,232000000,232070000,0.0,0.000000,232070500,29.0,215,0.210784,1020,0.210784
567,233090605,233000000,233090000,61.0,0.160105,233090600,381.0,414,0.368000,1125,0.207895
129,232040107,232000000,232040000,3.0,0.081081,232040100,37.0,26,0.276596,94,0.195515
318,232070407,232000000,232070000,0.0,0.000000,232070400,3.0,28,0.191781,146,0.191781
563,233090601,233000000,233090000,140.0,0.214395,233090600,653.0,707,0.404694,1747,0.190299
305,232070103,232000000,232070000,2.0,0.025641,232070100,78.0,129,0.209416,616,0.183775
168,232050905,232000000,232050000,43.0,0.065850,232050900,653.0,1016,0.241044,4215,0.175194
157,232050601,232000000,232050000,0.0,0.000000,232050600,35.0,207,0.171927,1204,0.171927
280,232063108,232000000,232060000,1.0,0.058824,232063100,17.0,13,0.228070,57,0.169247
1373,242030214,242000000,242030000,614.0,0.091355,242030200,6721.0,9408,0.259309,36281,0.167954
247,232062202,232000000,232060000,0.0,0.000000,232062200,2.0,4,0.166667,24,0.166667
145,232050206,232000000,232050000,17.0,0.033399,232050200,509.0,451,0.182222,2475,0.148823
150,232050304,232000000,232050000,1.0,0.015625,232050300,64.0,228,0.160225,1423,0.144600
683,235010110,235000000,235010000,197.0,0.095261,235010100,2068.0,10172,0.234632,43353,0.139371
131,232040109,232000000,232040000,55.0,0.164671,232040100,334.0,260,0.303738,856,0.139068
105,232010209,232000000,232010000,0.0,0.000000,232010200,5.0,24,0.137143,175,0.137143
381,233010501,233000000,233010000,426.0,0.068215,233010500,6245.0,9626,0.205053,46944,0.136838
1039,238070309,238000000,238070000,332.0,0.065445,238070300,5073.0,2258,0.199788,11302,0.134343
...,...,...,...,...,...,...,...,...,...,...,...
407,233020124,233000000,233020000,100.0,0.086059,233020100,1162.0,400,0.076879,5203,-0.009180
965,238030402,238000000,238030000,401.0,0.223772,238030400,1792.0,739,0.214327,3448,-0.009445
375,233010206,233000000,233010000,76.0,0.061940,233010200,1227.0,219,0.051421,4259,-0.010519
1105,239020504,239000000,239020000,3000.0,0.232144,239020500,12923.0,3536,0.221263,15981,-0.010881
1434,244010203,244000000,244010000,2902.0,0.149696,244010200,19386.0,3797,0.138769,27362,-0.010927
457,233040122,233000000,233040000,969.0,0.130911,233040100,7402.0,3830,0.118896,32213,-0.012014
680,235010106,235000000,235010000,602.0,0.135372,235010100,4447.0,1790,0.123109,14540,-0.012263
1460,244010803,244000000,244010000,11848.0,0.165906,244010800,71414.0,16934,0.153421,110376,-0.012485
438,233030601,233000000,233030000,951.0,0.158315,233030600,6007.0,3386,0.145484,23274,-0.012831
100,232010202,232000000,232010000,804.0,0.244898,232010200,3283.0,1557,0.229680,6779,-0.015218
107,232020103,232000000,232020000,1.0,0.066667,232020100,15.0,4,0.050633,79,-0.016034
6,231010401,231000000,231010000,3412.0,0.214093,231010400,15937.0,4217,0.194457,21686,-0.019636
1018,238070102,238000000,238070000,1111.0,0.185414,238070100,5992.0,1229,0.165410,7430,-0.020003
931,238010205,238000000,238010000,11.0,0.096491,238010200,114.0,28,0.074074,378,-0.022417
448,233040111,233000000,233040000,595.0,0.171816,233040100,3463.0,2484,0.147244,16870,-0.024573
399,233020116,233000000,233020000,38.0,0.106443,233020100,357.0,76,0.080937,939,-0.025505
452,233040117,233000000,233040000,616.0,0.172404,233040100,3573.0,2811,0.143962,19526,-0.028442
44,231030402,231000000,231030000,39.0,0.194030,231030400,201.0,227,0.164851,1377,-0.029179
933,238010208,238000000,238010000,10.0,0.140845,238010200,71.0,15,0.105634,142,-0.035211
21,231020101,231000000,231020000,1003.0,0.216959,231020100,4623.0,1157,0.181462,6376,-0.035497
682,235010108,235000000,235010000,5.0,0.108696,235010100,46.0,15,0.066667,225,-0.042029
454,233040119,233000000,233040000,6.0,0.098361,233040100,61.0,79,0.052667,1500,-0.045694
446,233040109,233000000,233040000,364.0,0.196650,233040100,1851.0,1812,0.150561,12035,-0.046090
462,233040127,233000000,233040000,7.0,0.129630,233040100,54.0,161,0.082480,1952,-0.047150
453,233040118,233000000,233040000,8.0,0.142857,233040100,56.0,33,0.092697,356,-0.050161
292,232063701,232000000,232060000,1.0,0.200000,232063700,5.0,9,0.136364,66,-0.063636
565,233090603,233000000,233090000,9.0,0.173077,233090600,52.0,93,0.083708,1111,-0.089369
576,233100106,233000000,233100000,134.0,0.261719,233100100,512.0,702,0.154252,4551,-0.107467
99,232010114,232000000,232010000,3.0,0.272727,232010100,11.0,5,0.135135,37,-0.137592
416,233020133,233000000,233020000,5.0,0.250000,233020100,20.0,31,0.065401,474,-0.184599

## # df2_re 데이터 정의 : 필요한 columns만 사용해서 가독성 높이자

In [46]:
# 이정도만 추려볼까?

df2_re = df2[['dcateCd','rcp_diff','rcp_x','rcp_y','totalOrderUserCnt_x','totalOrderUserCnt_y']].reset_index()

In [48]:
df2_re.head()

,index,dcateCd,rcp_diff,rcp_x,rcp_y,totalOrderUserCnt_x,totalOrderUserCnt_y
0,98,232010112,0.548803,0.118132,0.666935,728.0,2486
1,568,233090606,0.432881,0.040000,0.472881,50.0,590
2,124,232040102,0.371951,0.000000,0.371951,24.0,164
3,146,232050207,0.349552,0.014085,0.363636,71.0,330
4,564,233090602,0.340484,0.253012,0.593496,166.0,984

In [102]:
df2_re.to_csv('df2_re.csv')

---

## # user 변화가 많은 category도 살펴볼까?

In [80]:
df2.columns

Index(['dcateCd', 'lcateCd', 'mcateCd', 'moreT2TimesOrderUserCnt_x', 'rcp_x',
       'scateCd', 'totalOrderUserCnt_x', 'moreT2TimesOrderUserCnt_y', 'rcp_y',
       'totalOrderUserCnt_y', 'rcp_diff'],
      dtype='object')

In [86]:
dd = df2.totalOrderUserCnt_y -  df2.totalOrderUserCnt_x

In [88]:
sum(dd<0)   # 당연히 개입 user가 늘었겠지!

0

In [89]:
dd

98        1758.0
568        540.0
124        140.0
146        259.0
564        818.0
97         130.0
765     509306.0
158        915.0
196         41.0
104        125.0
135       1010.0
94        3119.0
323        991.0
567        744.0
129         57.0
318        143.0
563       1094.0
305        538.0
168       3562.0
157       1169.0
280         40.0
1373     29560.0
247         22.0
145       1966.0
150       1359.0
683      41285.0
131        522.0
105        170.0
381      40699.0
1039      6229.0
          ...
407       4041.0
965       1656.0
375       3032.0
1105      3058.0
1434      7976.0
457      24811.0
680      10093.0
1460     38962.0
438      17267.0
100       3496.0
107         64.0
6         5749.0
1018      1438.0
931        264.0
448      13407.0
399        582.0
452      15953.0
44        1176.0
933         71.0
21        1753.0
682        179.0
454       1439.0
446      10184.0
462       1898.0
453        300.0
292         61.0
565       1059.0
576       4039.0
99          26.0
416        454.0
Length: 1542, dtype: float64

In [92]:
df2[df2.rcp_diff>0].shape[0]

808

In [93]:
df2[df2.rcp_diff<0].shape[0]

128

In [94]:
df2[df2.rcp_diff==0].shape[0]

606

In [95]:
df2[df2.rcp_diff==0]

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt_x,rcp_x,scateCd,totalOrderUserCnt_x,moreT2TimesOrderUserCnt_y,rcp_y,totalOrderUserCnt_y,rcp_diff
1180,239030601,239000000,239030000,1177.0,0.056956,239030600,20665.0,1177,0.056956,20665,0.0
1472,244020203,244000000,244020000,376.0,0.108015,244020200,3481.0,376,0.108015,3481,0.0
1470,244020201,244000000,244020000,1.0,0.041667,244020200,24.0,1,0.041667,24,0.0
1471,244020202,244000000,244020000,136.0,0.114190,244020200,1191.0,136,0.114190,1191,0.0
1179,239030503,239000000,239030000,463.0,0.059943,239030500,7724.0,463,0.059943,7724,0.0
1181,239030602,239000000,239030000,14.0,0.066038,239030600,212.0,14,0.066038,212,0.0
1523,244030508,244000000,244030000,1104.0,0.074253,244030500,14868.0,1104,0.074253,14868,0.0
1490,244020605,244000000,244020000,72.0,0.100699,244020600,715.0,72,0.100699,715,0.0
1285,241010104,241000000,241010000,1147.0,0.333916,241010100,3435.0,1147,0.333916,3435,0.0
1336,242010101,242000000,242010000,14222.0,0.192039,242010100,74058.0,14222,0.192039,74058,0.0
1469,244020104,244000000,244020000,518.0,0.073517,244020100,7046.0,518,0.073517,7046,0.0
1178,239030502,239000000,239030000,386.0,0.051625,239030500,7477.0,386,0.051625,7477,0.0
1330,241030501,241000000,241030000,816.0,0.187414,241030500,4354.0,816,0.187414,4354,0.0
1329,241030404,241000000,241030000,968.0,0.089233,241030400,10848.0,968,0.089233,10848,0.0
1467,244020102,244000000,244020000,1745.0,0.121603,244020100,14350.0,1745,0.121603,14350,0.0
1185,239030606,239000000,239030000,1447.0,0.072249,239030600,20028.0,1447,0.072249,20028,0.0
1524,244030601,244000000,244030000,111524.0,0.360022,244030600,309770.0,111524,0.360022,309770,0.0
1187,239030701,239000000,239030000,1501.0,0.182715,239030700,8215.0,1501,0.182715,8215,0.0
1466,244020101,244000000,244020000,106.0,0.049602,244020100,2137.0,106,0.049602,2137,0.0
1191,239030801,239000000,239030000,59.0,0.054833,239030800,1076.0,59,0.054833,1076,0.0
1468,244020103,244000000,244020000,609.0,0.081482,244020100,7474.0,609,0.081482,7474,0.0
1175,239030403,239000000,239030000,219.0,0.062589,239030400,3499.0,219,0.062589,3499,0.0
1473,244020204,244000000,244020000,5.0,0.009488,244020200,527.0,5,0.009488,527,0.0
1474,244020205,244000000,244020000,418.0,0.082381,244020200,5074.0,418,0.082381,5074,0.0
1477,244020401,244000000,244020000,5650.0,0.159857,244020400,35344.0,5650,0.159857,35344,0.0
1153,239021207,239000000,239020000,1.0,0.027027,239021200,37.0,1,0.027027,37,0.0
1158,239030103,239000000,239030000,212.0,0.042130,239030100,5032.0,212,0.042130,5032,0.0
1159,239030104,239000000,239030000,119.0,0.048611,239030100,2448.0,119,0.048611,2448,0.0
1363,242030204,242000000,242030000,3824.0,0.111111,242030200,34416.0,3824,0.111111,34416,0.0
1476,244020301,244000000,244020000,3540.0,0.098725,244020300,35857.0,3540,0.098725,35857,0.0
...,...,...,...,...,...,...,...,...,...,...,...
719,235040106,235000000,235040000,19468.0,0.270644,235040100,71932.0,19468,0.270644,71932,0.0
720,235040107,235000000,235040000,6544.0,0.187900,235040100,34827.0,6544,0.187900,34827,0.0
109,232020105,232000000,232020000,5.0,0.049020,232020100,102.0,5,0.049020,102,0.0
721,235040108,235000000,235040000,29.0,0.064302,235040100,451.0,29,0.064302,451,0.0
722,235040110,235000000,235040000,46733.0,0.328647,235040100,142198.0,46733,0.328647,142198,0.0
723,235040111,235000000,235040000,407.0,0.099027,235040100,4110.0,407,0.099027,4110,0.0
724,235040201,235000000,235040000,329.0,0.081194,235040200,4052.0,329,0.081194,4052,0.0
725,235040301,235000000,235040000,102.0,0.071529,235040300,1426.0,102,0.071529,1426,0.0
726,235040302,235000000,235040000,12.0,0.260870,235040300,46.0,12,0.260870,46,0.0
708,235030108,235000000,235030000,0.0,0.000000,235030100,47.0,0,0.000000,47,0.0
709,235030110,235000000,235030000,7094.0,0.282720,235030100,25092.0,7094,0.282720,25092,0.0
696,235020201,235000000,235020000,110.0,0.153631,235020200,716.0,110,0.153631,716,0.0
700,235020405,235000000,235020000,72.0,0.119008,235020400,605.0,72,0.119008,605,0.0
690,235020104,235000000,235020000,2138.0,0.160246,235020100,13342.0,2138,0.160246,13342,0.0
992,238050302,238000000,238050000,964.0,0.059543,238050300,16190.0,964,0.059543,16190,0.0
691,235020106,235000000,235020000,930.0,0.145267,235020100,6402.0,930,0.145267,6402,0.0
692,235020107,235000000,235020000,755.0,0.114169,235020100,6613.0,755,0.114169,6613,0.0
693,235020108,235000000,235020000,7.0,0.059322,235020100,118.0,7,0.059322,118,0.0
694,235020110,235000000,235020000,4356.0,0.172426,235020100,25263.0,4356,0.172426,25263,0.0
695,235020111,235000000,235020000,208.0,0.077844,235020100,2672.0,208,0.077844,2672,0.0
697,235020304,235000000,235020000,148.0,0.107793,235020300,1373.0,148,0.107793,1373,0.0
698,235020401,235000000,235020000,411.0,0.110158,235020400,3731.0,411,0.110158,3731,0.0
699,235020403,235000000,235020000,53.0,0.069554,235020400,762.0,53,0.069554,762,0.0
936,238020102,238000000,238020000,1.0,0.006993,238020100,143.0,1,0.006993,143,0.0
701,235030101,235000000,235030000,42.0,0.066351,235030100,633.0,42,0.066351,633,0.0
702,235030102,235000000,235030000,75.0,0.105783,235030100,709.0,75,0.105783,709,0.0
703,235030103,235000000,235030000,5941.0,0.283080,235030100,20987.0,5941,0.283080,20987,0.0
706,235030106,235000000,235030000,4309.0,0.242569,235030100,17764.0,4309,0.242569,17764,0.0
705,235030105,235000000,235030000,866.0,0.132093,235030100,6556.0,866,0.132093,6556,0.0
704,235030104,235000000,235030000,16.0,0.062016,235030100,258.0,16,0.062016,258,0.0

---

---

## # 위에 했던것인데,  cur데이터에서 새로 추가된 category 만드는 방법에 대해서 다시 생각해본거야.

In [ ]:
cur.shape

In [15]:
prev_live.shape

(1542, 7)

In [17]:
prev_live.dcateCd

5465    231010101
5466    231010201
5467    231010202
5468    231010203
5469    231010204
5470    231010301
5471    231010401
5472    231010402
5473    231010403
5474    231010404
5475    231010405
5476    231010501
5477    231010502
5478    231010503
5479    231010601
5480    231010602
5481    231010603
5482    231010604
5483    231010605
5484    231010606
5485    231010607
5486    231020101
5487    231020102
5488    231020201
5489    231020202
5490    231020203
5491    231020301
5492    231020302
5493    231020303
5494    231020304
          ...
6977    244030206
6978    244030301
6979    244030401
6980    244030402
6981    244030501
6982    244030502
6983    244030503
6984    244030504
6985    244030505
6986    244030506
6987    244030507
6988    244030508
6989    244030601
6990    244030602
6991    244030603
6992    244030604
6993    244030605
6994    244030606
6995    244030607
6996    244030701
6997    244030702
6998    244030801
6999    244030802
7000    244030803
7001    244030804
7002    244030805
7003    244030806
7004    244030901
7005    244030902
7006    245010101
Name: dcateCd, Length: 1542, dtype: int64

In [19]:
cur[(~cur.dcateCd.isin(prev_live.dcateCd))].shape

(33, 7)

In [20]:
cur[(~cur.dcateCd.isin(prev_live.dcateCd))]

,dcateCd,lcateCd,mcateCd,moreT2TimesOrderUserCnt,rcp,scateCd,totalOrderUserCnt
92,232010105,232000000,232010000,2,0.500000,232010100,4
101,232010201,232000000,232010000,8,0.063492,232010200,126
103,232010203,232000000,232010000,4,0.137931,232010200,29
109,232020101,232000000,232020000,5,0.384615,232020100,13
121,232030504,232000000,232030000,553,0.172921,232030500,3198
202,232060504,232000000,232060000,1,0.013699,232060500,73
221,232061201,232000000,232060000,21,0.192661,232061200,109
248,232062004,232000000,232060000,1,0.083333,232062000,12
287,232063106,232000000,232060000,22,0.372881,232063100,59
290,232063109,232000000,232060000,5,0.333333,232063100,15
312,232064001,232000000,232060000,65,0.224138,232064000,290
313,232064003,232000000,232060000,4,0.102564,232064000,39
314,232064004,232000000,232060000,9,0.195652,232064000,46
315,232064005,232000000,232060000,13,0.109244,232064000,119
334,232070409,232000000,232070000,2,0.071429,232070400,28
335,232070410,232000000,232070000,7,0.125000,232070400,56
337,232070412,232000000,232070000,30,0.125523,232070400,239
466,233040112,233000000,233040000,317,0.072490,233040100,4373
470,233040116,233000000,233040000,14,0.041420,233040100,338
698,235010103,235000000,235010000,263,0.134184,235010100,1960
700,235010105,235000000,235010000,896,0.119007,235010100,7529
705,235010111,235000000,235010000,956,0.153550,235010100,6226
707,235010401,235000000,235010000,794,0.105923,235010400,7496
708,235010402,235000000,235010000,240,0.130364,235010400,1841
709,235010403,235000000,235010000,345,0.116593,235010400,2959
712,235010504,235000000,235010000,431,0.110089,235010500,3915
713,235010505,235000000,235010000,742,0.171521,235010500,4326
959,238010206,238000000,238010000,0,0.000000,238010200,5
1032,238060201,238000000,238060000,0,0.000000,238060200,3
1036,238060301,238000000,238060000,26,0.037627,238060300,691
1037,238060302,238000000,238060000,259,0.119190,238060300,2173
1090,239010203,239000000,239010000,1,0.111111,239010200,9
1107,239010603,239000000,239010000,1,0.125000,239010600,8